<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access Token' => '',
    'Are you sure you want to delete this item?' => '',
    'Auth Key' => '',
    'Caixa Has Vendas' => '',
    'Caixa Idcaixa' => '',
    'Caixas' => '',
    'Categoria Idcategoria' => '',
    'Categorias' => '',
    'Cpf' => '',
    'Create Caixa' => '',
    'Create Caixa Has Venda' => '',
    'Create Categoria' => '',
    'Create Funcionario' => '',
    'Create Mesa' => '',
    'Create Pagamento' => '',
    'Create Produto' => '',
    'Create Usuario' => '',
    'Create Venda' => '',
    'Create Venda Has Produto' => '',
    'Data' => '',
    'Delete' => '',
    'Descricao' => '',
    'Funcionario Idfuncionario' => '',
    'Funcionarios' => '',
    'Idcaixa' => '',
    'Idcategoria' => '',
    'Idfuncionario' => '',
    'Idmesa' => '',
    'Idpagamento' => '',
    'Idproduto' => '',
    'Idusuario' => '',
    'Idvenda' => '',
    'Manager' => '',
    'Mesa Idmesa' => '',
    'Mesas' => '',
    'Nome Func' => '',
    'Nomecategoria' => '',
    'Nomeproduto' => '',
    'Numero Mesa' => '',
    'Pagamentos' => '',
    'Password' => '',
    'Preco' => '',
    'Produto Idproduto' => '',
    'Produtos' => '',
    'Quantidade' => '',
    'Reset' => '',
    'Save' => '',
    'Search' => '',
    'Select the types of user' => '',
    'Status' => '',
    'Subtotal' => '',
    'The requested page does not exist.' => '',
    'Type' => '',
    'Update' => '',
    'Update Caixa Has Venda: mode' => '',
    'Update Caixa: mode' => '',
    'Update Categoria: mode' => '',
    'Update Funcionario: mode' => '',
    'Update Mesa: mode' => '',
    'Update Pagamento: mode' => '',
    'Update Produto: mode' => '',
    'Update Usuario: mode' => '',
    'Update Venda Has Produto: mode' => '',
    'Update Venda: mode' => '',
    'Username' => '',
    'Usuario Idusuario' => '',
    'Usuarios' => '',
    'Valor' => '',
    'Valor Total' => '',
    'Valor Uni' => '',
    'Venda Has Produtos' => '',
    'Venda Idvenda' => '',
    'Vendas' => '',
    'employee' => '',
];
